# Generated by Django 6.0.2 on 2026-03-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('taken', 'Taken'), ('received', 'Received'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
